package com.trustgrid.api.risk;

public enum RiskDecision {
    ALLOW,
    ALLOW_WITH_LIMITS,
    REQUIRE_EXTRA_EVIDENCE,
    REQUIRE_VERIFICATION,
    REQUIRE_MANUAL_REVIEW,
    HIDE_LISTING,
    BLOCK_TRANSACTION,
    RESTRICT_CAPABILITY,
    SUSPEND_ACCOUNT,
    SUPPRESS_REVIEW_WEIGHT
}
