package com.trustgrid.api.transaction;

public enum TransactionStatus {
    REQUESTED,
    ACCEPTED,
    SCHEDULED,
    IN_PROGRESS,
    COMPLETION_CLAIMED,
    BUYER_CONFIRMED,
    COMPLETED,
    CANCELLED,
    NO_SHOW_REPORTED,
    DISPUTED,
    PURCHASED,
    SHIPPED,
    DELIVERED,
    CONFIRMATION_WINDOW_OPEN,
    RETURN_REQUESTED,
    POSTED,
    PROOF_UPLOADED,
    REQUESTER_CONFIRMED,
    ACCEPTED_BY_SHOPPER,
    PURCHASE_PROOF_UPLOADED,
    DELIVERY_PROOF_UPLOADED
}
