package com.trustgrid.api.evidence;

public enum EvidenceType {
    LISTING_PHOTO,
    RECEIPT,
    DELIVERY_PROOF,
    BEFORE_PHOTO,
    AFTER_PHOTO,
    CHAT_EXCERPT,
    SERVICE_COMPLETION_NOTE,
    CANCELLATION_REASON,
    MODERATOR_NOTE,
    USER_STATEMENT,
    PURCHASE_PROOF_PLACEHOLDER,
    DELIVERY_PROOF_PLACEHOLDER
}
