package com.trustgrid.api.listing;

public enum ListingLifecycleEventType {
    LISTING_CREATED,
    LISTING_SUBMITTED,
    LISTING_PUBLISHED,
    LISTING_UNDER_REVIEW,
    LISTING_HIDDEN,
    LISTING_REJECTED,
    LISTING_EXPIRED,
    LISTING_UPDATED,
    LISTING_RESTORED,
    LISTING_EVIDENCE_REQUIRED,
    LISTING_RISK_SNAPSHOT_RECORDED,
    DUPLICATE_LISTING_DETECTED
}
