alter table capability_governance_timeline_events drop constraint if exists chk_capability_governance_timeline_event;
alter table capability_governance_timeline_events add constraint chk_capability_governance_timeline_event check (event_type in (
    'CAPABILITY_POLICY_CREATED', 'CAPABILITY_SIMULATED', 'TEMPORARY_GRANT_CREATED',
    'TEMPORARY_GRANT_REVOKED', 'TEMPORARY_GRANT_EXPIRED', 'BREAK_GLASS_CREATED',
    'BREAK_GLASS_REVOKED', 'BREAK_GLASS_EXPIRED', 'CAPABILITY_DECISION_LOGGED',
    'CAPABILITY_DECISION_REPLAYED', 'CAPABILITY_BLAST_RADIUS_PREVIEWED'
));

alter table data_repair_recommendations drop constraint if exists chk_data_repair_type;
alter table data_repair_recommendations add constraint chk_data_repair_type check (repair_type in (
    'REBUILD_REPUTATION', 'REBUILD_SEARCH_INDEX', 'REBUILD_LINEAGE',
    'MARK_EVIDENCE_REFERENCE_INVALID', 'REQUEST_OPERATOR_REVIEW',
    'RESTORE_CAPABILITY_ALIGNMENT', 'REPLAY_EVENTS', 'MANUAL_REPAIR_REQUIRED',
    'EXPIRE_TEMPORARY_CAPABILITY_GRANT', 'EXPIRE_BREAK_GLASS_CAPABILITY_ACTION',
    'REQUEST_CAPABILITY_DECISION_REVIEW', 'REVOKE_GRANT_FOR_CLOSED_PARTICIPANT',
    'REVOKE_BREAK_GLASS_FOR_CLOSED_PARTICIPANT'
));

alter table operator_data_repair_actions drop constraint if exists chk_operator_repair_action;
alter table operator_data_repair_actions add constraint chk_operator_repair_action check (action_type in (
    'APPLY_REBUILD_REPUTATION', 'APPLY_REBUILD_SEARCH_INDEX', 'APPLY_REBUILD_LINEAGE',
    'MARK_FINDING_RESOLVED', 'RECORD_MANUAL_REPAIR', 'REJECT_RECOMMENDATION',
    'EXPIRE_TEMPORARY_CAPABILITY_GRANT', 'EXPIRE_BREAK_GLASS_CAPABILITY_ACTION',
    'REQUEST_CAPABILITY_DECISION_REVIEW', 'REVOKE_GRANT_FOR_CLOSED_PARTICIPANT',
    'REVOKE_BREAK_GLASS_FOR_CLOSED_PARTICIPANT'
));

alter table marketplace_events drop constraint if exists chk_marketplace_events_v8_type;
alter table marketplace_events add constraint chk_marketplace_events_v9_type check (event_type in (
    'PARTICIPANT_CREATED', 'PROFILE_UPDATED', 'CAPABILITY_GRANTED', 'CAPABILITY_REVOKED', 'CAPABILITY_RESTRICTED',
    'VERIFICATION_STATUS_UPDATED', 'ACCOUNT_STATUS_UPDATED', 'RESTRICTION_APPLIED', 'RESTRICTION_REMOVED',
    'TRUST_PROFILE_INITIALIZED', 'TRUST_PROFILE_UPDATED',
    'LISTING_CREATED', 'LISTING_SUBMITTED', 'LISTING_PUBLISHED', 'LISTING_UNDER_REVIEW', 'LISTING_HIDDEN',
    'LISTING_REJECTED', 'LISTING_EXPIRED', 'LISTING_UPDATED', 'LISTING_RESTORED', 'LISTING_EVIDENCE_REQUIRED',
    'LISTING_RISK_SNAPSHOT_RECORDED', 'DUPLICATE_LISTING_DETECTED',
    'TRANSACTION_CREATED', 'TRANSACTION_ACCEPTED', 'TRANSACTION_STARTED', 'TRANSACTION_SHIPPED',
    'TRANSACTION_DELIVERED', 'TRANSACTION_PROOF_PLACEHOLDER_RECORDED', 'TRANSACTION_CANCELLED',
    'TRANSACTION_COMPLETION_CLAIMED', 'TRANSACTION_CONFIRMED', 'TRANSACTION_COMPLETED',
    'TRANSACTION_NO_SHOW_REPORTED', 'TRANSACTION_RISK_SNAPSHOT_RECORDED', 'TRANSACTION_DEADLINE_CREATED',
    'TRANSACTION_DEADLINE_SATISFIED', 'TRANSACTION_DEADLINE_CANCELLED', 'TRANSACTION_INVARIANT_CHECK_RUN',
    'EVIDENCE_RECORDED', 'EVIDENCE_REQUIREMENT_CREATED', 'EVIDENCE_REQUIREMENT_SATISFIED', 'EVIDENCE_BUNDLE_GENERATED',
    'DISPUTE_OPENED', 'DISPUTE_STATUS_UPDATED', 'DISPUTE_STATEMENT_ADDED', 'DISPUTE_EVIDENCE_DEADLINE_CREATED',
    'DISPUTE_EVIDENCE_DEADLINE_MISSED', 'DISPUTE_RESOLVED', 'DISPUTE_CLOSED',
    'REVIEW_CREATED', 'REVIEW_SUPPRESSED', 'REPUTATION_RECALCULATED', 'TRUST_TIER_CHANGED',
    'RISK_DECISION_RECORDED', 'OFF_PLATFORM_CONTACT_REPORTED', 'RISK_ACTION_RECOMMENDED',
    'RANKING_DECISION_LOGGED', 'RANKING_REPLAYED',
    'REVIEW_GRAPH_EDGE_CREATED', 'REVIEW_ABUSE_CLUSTER_DETECTED', 'REVIEW_WEIGHT_SUPPRESSED', 'TRUST_GRAPH_RISK_RECORDED',
    'OPS_QUEUE_ITEM_CREATED', 'OPS_QUEUE_ITEM_UPDATED', 'MODERATOR_ACTION_RECORDED', 'MANUAL_REVIEW_CASE_CREATED',
    'MANUAL_REVIEW_STATUS_UPDATED', 'SAFETY_ESCALATION_CREATED', 'ACCOUNT_RESTRICTION_WORKFLOW_UPDATED',
    'PAYMENT_BOUNDARY_STATE_CHANGED', 'MARKETPLACE_FUNDS_RELEASE_REQUESTED', 'MARKETPLACE_REFUND_REQUESTED',
    'MARKETPLACE_PAYOUT_HOLD_REQUESTED', 'MARKETPLACE_TRANSACTION_CLOSED',
    'ANALYTICS_EVENT_INGESTED', 'REPUTATION_DRIFT_DETECTED', 'REPUTATION_REBUILD_RUN', 'SEARCH_INDEX_REBUILD_RUN',
    'EVIDENCE_CONSISTENCY_CHECK_RUN', 'OUTBOX_REPLAY_RUN', 'AUDIT_TIMELINE_REPLAY_RUN', 'SCAM_SIMULATION_RUN',
    'BENCHMARK_RUN', 'FAILURE_MATRIX_RUN',
    'TRUST_POLICY_VERSION_CREATED', 'POLICY_SIMULATION_RUN', 'SHADOW_RISK_DECISION_RECORDED',
    'COUNTERFACTUAL_RANKING_SIMULATED', 'DISPUTE_DECISION_SIMULATED', 'APPEAL_OPENED', 'APPEAL_DECIDED',
    'POLICY_RULE_CREATED', 'POLICY_APPROVAL_REQUESTED', 'POLICY_APPROVAL_RECORDED', 'POLICY_ACTIVATED',
    'POLICY_RETIRED', 'POLICY_ROLLBACK_COMPLETED', 'POLICY_EXCEPTION_REQUESTED', 'POLICY_EXCEPTION_APPROVED',
    'POLICY_EXCEPTION_REJECTED', 'POLICY_EXCEPTION_REVOKED', 'POLICY_DECISION_RECORDED',
    'POLICY_BLAST_RADIUS_PREVIEWED', 'POLICY_REGRESSION_CHECK_RUN',
    'TRUST_TELEMETRY_RECORDED', 'TRUST_SLO_BREACHED',
    'TRUST_INCIDENT_CREATED', 'TRUST_INCIDENT_UPDATED', 'TRUST_INCIDENT_RESOLVED', 'TRUST_INCIDENT_REPLAYED',
    'TRUST_ALERT_CREATED', 'TRUST_ALERT_ACKNOWLEDGED', 'OPS_DASHBOARD_AGGREGATED',
    'TRUST_SCORE_LINEAGE_RECORDED', 'RANKING_LINEAGE_RECORDED', 'POLICY_LINEAGE_RECORDED', 'LINEAGE_REBUILD_RUN',
    'CONSISTENCY_CHECK_RUN', 'DATA_REPAIR_RECOMMENDED', 'OPERATOR_DATA_REPAIR_APPLIED',
    'CAPABILITY_POLICY_CREATED', 'CAPABILITY_SIMULATED', 'TEMPORARY_CAPABILITY_GRANT_CREATED',
    'TEMPORARY_CAPABILITY_GRANT_REVOKED', 'TEMPORARY_CAPABILITY_GRANT_EXPIRED',
    'BREAK_GLASS_CAPABILITY_CREATED', 'BREAK_GLASS_CAPABILITY_REVOKED', 'BREAK_GLASS_CAPABILITY_EXPIRED',
    'CAPABILITY_DECISION_LOGGED', 'CAPABILITY_GOVERNANCE_TIMELINE_RECORDED',
    'CAPABILITY_DECISION_REPLAYED', 'CAPABILITY_BLAST_RADIUS_PREVIEWED'
));
