package com.trustgrid.api.dispute;

public enum DisputeType {
    ITEM_NOT_RECEIVED,
    ITEM_NOT_AS_DESCRIBED,
    COUNTERFEIT_SUSPECTED,
    SERVICE_NOT_DELIVERED,
    NO_SHOW,
    WRONG_ITEM_PURCHASED,
    SHOPPER_DID_NOT_BUY,
    BUYER_FALSE_CLAIM,
    SELLER_FALSE_CLAIM,
    SAFETY_CONCERN,
    OFF_PLATFORM_PAYMENT_ATTEMPT
}
